#!/usr/bin/env bash
set -Eeuo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

cd "$ROOT_DIR"

log "contract-drift: verifying generated event contract shape"
python3 - <<'PY'
import json
from pathlib import Path
import tomllib

root = Path(".")
generated = json.loads((root / "contracts/events/jcp-envelope.schema.json").read_text())
canonical = json.loads((root / "schemas/jcp/1.0.0/jcp.schema.json").read_text())
tips_jcp = json.loads((root / "tips/v6/JCP_1_0_0_Protocol.schema.json").read_text())

required = [
    "jcp_version",
    "kind",
    "message_id",
    "message_type",
    "producer",
    "subject",
    "time",
    "trace",
    "authority",
    "policy",
    "data",
    "payload_hash",
    "payload",
    "signature",
]

expected = dict(canonical)
expected["$id"] = "https://schemas.neverhuman.ai/jmcp/events/jcp-envelope.schema.json"
expected["$comment"] = "Generated by: just contract-drift. Source: schemas/jcp/1.0.0/jcp.schema.json. DO NOT EDIT BY HAND."
expected["title"] = "JCPEnvelope"

if canonical != tips_jcp:
    raise SystemExit("schemas/jcp/1.0.0/jcp.schema.json must match tips/v6/JCP_1_0_0_Protocol.schema.json")
if generated != expected:
    raise SystemExit("generated event contract drifted from canonical JCP schema")
if generated["$id"] != "https://schemas.neverhuman.ai/jmcp/events/jcp-envelope.schema.json":
    raise SystemExit("generated event contract has the wrong $id")
if generated["$schema"] != "https://json-schema.org/draft/2020-12/schema":
    raise SystemExit("generated event contract must use draft 2020-12")
if generated["type"] != "object":
    raise SystemExit("generated event contract must describe an object")
if generated["additionalProperties"] is not False:
    raise SystemExit("generated event contract must forbid extra properties")
if generated["required"] != required:
    raise SystemExit("generated event contract required fields drifted")
if canonical["required"] != required:
    raise SystemExit("canonical JCP schema required fields drifted")
if generated["$comment"] != "Generated by: just contract-drift. Source: schemas/jcp/1.0.0/jcp.schema.json. DO NOT EDIT BY HAND.":
    raise SystemExit("generated event contract is missing the generated marker")
if generated["properties"]["jcp_version"]["const"] != "1.0.0":
    raise SystemExit("generated event contract must require JCP/1.0.0")
if generated["properties"]["kind"]["const"] != "JCPEnvelope":
    raise SystemExit("generated event contract must describe JCPEnvelope")

zones = tomllib.loads((root / "agent/generated-zones.toml").read_text()).get("zone", [])
if len(zones) != 1:
    raise SystemExit("generated zones should declare only concrete generated files")
exact = next((zone for zone in zones if zone.get("path") == "contracts/events/jcp-envelope.schema.json"), None)
if exact is None:
    raise SystemExit("missing generated zone for contracts/events/jcp-envelope.schema.json")
if exact.get("command") != "just contract-drift":
    raise SystemExit("event contract zone must point at `just contract-drift`")
source = exact.get("source", "")
if "schemas/jcp/1.0.0/jcp.schema.json" not in source:
    raise SystemExit("event contract zone must declare the canonical schema source")
if "contracts/events/jcp-envelope.schema.json" not in source:
    raise SystemExit("event contract zone must declare the generated contract path for auditor ownership checks")
if exact.get("kind") != "event-contract":
    raise SystemExit("event contract zone must be tagged as an event contract")
if exact.get("required_marker") != "Generated by: just contract-drift. Source: schemas/jcp/1.0.0/jcp.schema.json. DO NOT EDIT BY HAND.":
    raise SystemExit("event contract zone must declare the generated marker")
if exact.get("allowed") is not True:
    raise SystemExit("event contract zone must be allowed generated output")

readme = (root / "contracts/events/README.md").read_text()
if "generated contract output" not in readme:
    raise SystemExit("contracts/events/README.md must describe the generated surface")
if "just contract-drift" not in readme:
    raise SystemExit("contracts/events/README.md must point at the proof command")
PY

log "contract-drift: complete"
