#!/usr/bin/env bash
set -Eeuo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

cd "$ROOT_DIR"

log "contract-drift: verifying generated event contract shape"
python3 - <<'PY'
import json
from pathlib import Path
import tomllib

root = Path(".")
generated = json.loads((root / "contracts/events/jcp-envelope.schema.json").read_text())
canonical = json.loads((root / "schemas/jcp/1.0.0/jcp.schema.json").read_text())
tips_jcp = json.loads((root / "tips/v6/JCP_1_0_0_Protocol.schema.json").read_text())

required = [
    "jcp_version",
    "kind",
    "message_id",
    "message_type",
    "producer",
    "subject",
    "time",
    "trace",
    "authority",
    "policy",
    "data",
    "payload_hash",
    "payload",
    "signature",
]

expected = dict(canonical)
expected["$id"] = "https://schemas.neverhuman.ai/jmcp/events/jcp-envelope.schema.json"
expected["$comment"] = "Generated by: just contract-drift. Source: schemas/jcp/1.0.0/jcp.schema.json. DO NOT EDIT BY HAND."
expected["title"] = "JCPEnvelope"

if canonical != tips_jcp:
    raise SystemExit("schemas/jcp/1.0.0/jcp.schema.json must match tips/v6/JCP_1_0_0_Protocol.schema.json")
if generated != expected:
    raise SystemExit("generated event contract drifted from canonical JCP schema")
if generated["$id"] != "https://schemas.neverhuman.ai/jmcp/events/jcp-envelope.schema.json":
    raise SystemExit("generated event contract has the wrong $id")
if generated["$schema"] != "https://json-schema.org/draft/2020-12/schema":
    raise SystemExit("generated event contract must use draft 2020-12")
if generated["type"] != "object":
    raise SystemExit("generated event contract must describe an object")
if generated["additionalProperties"] is not False:
    raise SystemExit("generated event contract must forbid extra properties")
if generated["required"] != required:
    raise SystemExit("generated event contract required fields drifted")
if canonical["required"] != required:
    raise SystemExit("canonical JCP schema required fields drifted")
if generated["$comment"] != "Generated by: just contract-drift. Source: schemas/jcp/1.0.0/jcp.schema.json. DO NOT EDIT BY HAND.":
    raise SystemExit("generated event contract is missing the generated marker")
if generated["properties"]["jcp_version"]["const"] != "1.0.0":
    raise SystemExit("generated event contract must require JCP/1.0.0")
if generated["properties"]["kind"]["const"] != "JCPEnvelope":
    raise SystemExit("generated event contract must describe JCPEnvelope")

zones = tomllib.loads((root / "agent/generated-zones.toml").read_text()).get("zone", [])
zones_by_path = {zone.get("path"): zone for zone in zones}

def assert_zone(path, kind, required_marker, source_parts):
    exact = zones_by_path.get(path)
    if exact is None:
        raise SystemExit(f"missing generated zone for {path}")
    if exact.get("command") != "just contract-drift":
        raise SystemExit(f"{path} zone must point at `just contract-drift`")
    source = exact.get("source", "")
    for part in source_parts:
        if part not in source:
            raise SystemExit(f"{path} zone source must mention {part}")
    if exact.get("kind") != kind:
        raise SystemExit(f"{path} zone must be tagged as {kind}")
    if exact.get("required_marker") != required_marker:
        raise SystemExit(f"{path} zone must declare the required marker")
    if exact.get("allowed") is not True:
        raise SystemExit(f"{path} zone must be allowed generated output")
    if required_marker not in (root / path).read_text():
        raise SystemExit(f"{path} is missing its generated-zone marker")

assert_zone(
    "contracts/events/jcp-envelope.schema.json",
    "event-contract",
    "Generated by: just contract-drift. Source: schemas/jcp/1.0.0/jcp.schema.json. DO NOT EDIT BY HAND.",
    [
        "schemas/jcp/1.0.0/jcp.schema.json",
        "contracts/events/jcp-envelope.schema.json",
    ],
)
assert_zone(
    "contracts/openapi/jmcp-api.openapi.yaml",
    "http-contract",
    "Contract zone: verified by just contract-drift. Source: crates/jmcp-api/src/routes.rs + jmcp-domain/jcp-core serde types. DO NOT EDIT WITHOUT ROUTE COVERAGE.",
    [
        "crates/jmcp-api/src/routes.rs",
        "contracts/openapi/jmcp-api.openapi.yaml",
    ],
)
assert_zone(
    "contracts/asyncapi/jmcp-streams.asyncapi.yaml",
    "stream-contract",
    "Contract zone: verified by just contract-drift. Source: jmcp-api streaming routes + jmcp-domain serde types. DO NOT EDIT WITHOUT ROUTE COVERAGE.",
    [
        "crates/jmcp-api/src/jitux.rs",
        "contracts/asyncapi/jmcp-streams.asyncapi.yaml",
    ],
)

readme = (root / "contracts/events/README.md").read_text()
if "generated contract output" not in readme:
    raise SystemExit("contracts/events/README.md must describe the generated surface")
if "just contract-drift" not in readme:
    raise SystemExit("contracts/events/README.md must point at the proof command")
PY

log "contract-drift: validating authored OpenAPI and AsyncAPI YAML"
ruby -e 'require "yaml"; YAML.load_file("contracts/openapi/jmcp-api.openapi.yaml"); YAML.load_file("contracts/asyncapi/jmcp-streams.asyncapi.yaml")'

log "contract-drift: checking HTTP route and streaming contract coverage"
cargo test -p jmcp-api --test openapi_route_coverage --locked

log "contract-drift: complete"
